### ISSUE TITLE
Consider publishing jar to Maven Central

### ISSUE THREAD

**Issue by Walliee** [promregator/promregator#102]
## Summary / Problem Statement
Great job on this tool! Are there plans on making it available in Maven Central?

**Comment by eaglerainbow** [comment]
Hi Anshul,

> Great job on this tool!

Thank you for the compliment!

> Are there plans on making it available in Maven Central?

So far not, but you may change this with this issue here 😀 

We currently have the two delivery channels
* (uber-)JAR file for download from github, and
* docker image via docker hub.

I currently don't see a case, why also uploading it maven central would bring some benefit: Promregator is neither a library, against which you wanted to bind, nor are we compliant to the maven lifecycle/it is a maven plugin.
But perhaps I miss an aspect where having it uploaded/distributed over there would make sense.

So, perhaps let's start the discussion with the question: "Why do you ask for it"? 😄

**Comment by Walliee** [comment]
If I were to use this for a personal project, nothing could be simpler than just download the jar from GitHub and use it. 

However, it's not possible for me to do that at work and much harder to do get additional source of software artifacts added so that they become available in the internal mirror. An artifact that is published to a popular Maven Central repo would automatically flow to the internal mirror.

I imagine other firms also have such controls in place and think having the uber JAR available in Maven Central would therefore add value.

**Comment by eaglerainbow** [comment]
I will check how much effort it would be for Promregator to get deployed to such an official mirror. 
However, I feel bad by supporting company policies where you can't download anything (e.g. via corporate proxy) from the web (using a browser), but at the same time they would feed the company's internal mirror with every crap from the internet, which apparently then doesn't go through the same restrictive web filtering mechanism. Eventually all the Java-based repositories are just http(s) servers, too. So that is either inconsistent or feels somewhat loophole-ish to me.

**Comment by eaglerainbow** [comment]
Links to info material: https://maven.apache.org/repository/guide-central-repository-upload.html
https://central.sonatype.org/pages/ossrh-guide.html

Several things to do:
* Signup at OSSH
* PGP Handling for signing also JAR artifacts (see also http://central.sonatype.org/pages/working-with-pgp-signatures.html)
* Clarify on Promregator groupId Namespace / check on [coordinates](http://central.sonatype.org/pages/choosing-your-coordinates.html)
* Check on [additional requirements](https://central.sonatype.org/pages/requirements.html)
* Add license declaration (Apache)

**Comment by eaglerainbow** [comment]
Claiming our namespace with https://issues.sonatype.org/browse/OSSRH-48665

**Comment by eaglerainbow** [comment]
Note that https://issues.sonatype.org/browse/OSSRH-48665 requests to be informed as soon as the first artifact was deployed (which may still take a while).

**Comment by eaglerainbow** [comment]
With 777c8cfce98f4f52ea373db6b50e36d4ff5f4024 everything should be prepared now (was a little more effort than I had thought initially).

I am currently targeting 0.6.0 to deliver a first version to maven central.

**Comment by eaglerainbow** [comment]
Starting with 0.6.0, all versions will be published primarily at https://oss.sonatype.org/#nexus-search;quick~com.github.promregator and will be replicated to Maven Central automatically.
