### ISSUE TITLE
promregator is failing in docker-ce 19.03.0

### ISSUE THREAD

**Issue by chewrocca** [promregator/promregator#113]
## Environment
Promregator 0.5.7 running in Docker Swarm environment running on RedHat 7 systems.  

## Summary / Problem Statement
Promregator starts up and appears to function as normal until it appears to hang shortly after the first Prometheus scrape.  I can access /promregatorMetrics but /metrics and /discovery endpoints fail.  `docker logs <containerID>` also states "error from daemon in stream: Error grabbing logs: error decoding log message: unexpected EOF".   

## Observed Behavior
As soon as the docker logs report that issue above and drops back to shell prompt, Promregator appears to hang.  Attempting to use docker stop will not stop the running Promregator behavior.  

## Expected Behavior
I would expect this to work the same way as it does in 18.09.6.  Not sure what changed.

**Comment by eaglerainbow** [comment]
Hi,

Welcome to Promregator and thanks for reporting your issue!
Unfortunately, even after reading your description, I still have my doubts whether I understood everything properly. That's why here is what I think I understood:

* You have been using Promregator 0.5.7 on Docker Swarm (w/ RedHat 7) before, where docker-ce 18.09.6 was running.
* You upgraded docker-ce to 19.03.0. Afterwards, you are facing issues now.
* You checked that the same image is in use.
* You can access `/promregatorMetrics`, which returns "some data" (which?) 
* You cannot access the other scraping endpoints (`/metrics` and `/discovery`) - What is the exact error message/HTTP response code? 

Please correct me, in case anything above would be wrong. 

Additionally, it might be interesting if you could collect the following information and paste it here (if necessary anonymized):

* What does `docker stats` on the Swarm node say? How much memory/CPU is being consumed?
* Are are you able to `docker exec -ti <containerid> /bin/bash` into the container successfully? If yes, what does `top` and `ps auxww` say there? Can you reach your scraping targets from here?
* Please have a look at `/var/log/syslog` on the machine, if scraping starts to fail. Is there anything noteworthy?

I hope that with these data we might get some hints on what is going wrong with your case.

PS: I would not know anything that Promregator does which could provoke such an effect. It more feels to me that this is a docker-ce-related issue itself. I am willing to assist you, but I have my doubts that I will be of great help. Therefore, please also consider raising a ticket https://github.com/docker/for-linux for your case. The folks there might be able to support you better than I will be able to do.

**Comment by eaglerainbow** [comment]
> docker logs <containerID> also states "error from daemon in stream: Error grabbing logs: error decoding log message: unexpected EOF".

That sounds very wired. Stupid question: Did you check free disk space on the machine?

**Comment by chewrocca** [comment]
I'm going to close this issue.  It appears to be related to a logging plugin called Loki.  When the logs abruptly stop I see the following in /var/log/messages: 

```dockerd: time="2019-07-29T11:54:30-05:00" level=error msg="panic: runtime error: invalid memory address or nil pointer dereference" plugin=632b0fdf56fd6349a1abc7b730eb1a5f1674d1c7935f37b6fc32e577eedadf29```

**Comment by chewrocca** [comment]
For what it's worth, this was related to a docker plugin after 18.09.7+.  https://github.com/grafana/loki/issues/812 thanks again for looking at this.

**Comment by eaglerainbow** [comment]
Thanks for reporting back here - and great that you got it fixed by the folks over at loki so fast! 
Enjoy using Promregator!
