### ISSUE TITLE
Thread / DirectByteBuffer Increase for Each ERRONEOUS_GET_INFO_RESPONSE in ReactiveCFAccessorImpl.connectionWatchdog 

### ISSUE THREAD

**Issue by mickey-hill** [promregator/promregator#161]
## Environment
promregator 7.2

## Summary / Problem Statement

ReactiveCFAccessorImpl.resetCloudFoundryClient causes the creation of a duplicative cloudfoundry-client-nio threads with each call.  I have not encountered a limit in how many of these threads will be created (I observed many hundreds and still growing).

ReactiveCFAccessorImpl.resetCloudFoundryClient is called in the ReactiveCFAccessorImpl.connectionWatchdog method for any ERRONEOUS_GET_INFO_RESPONSE.  This includes seemingly recoverable issues such as timed-out calls to the CF API.  

Additionally, with the increasing nio threads comes more DirectByteBuffers.  In a small-footprint environment (e.g. deployed on cloud foundry with 2 GB of memory allocated), the DirectByteBuffers can reach a default max and lead to OutOfMemoryErrors.

Scenarios with repeated connectionWatchdog failures can destabilize promregator relatively quickly.

It seems as though resetCloudFoundryClient should either stop existing cloudfoundry-client-nio threads, or have a max count setting.  A recommended -XX:MaxDirectMemorySize setting would be useful too.

## Observed Behavior
8 cloudfoundry-client-nio threads created for each call to ReactiveCFAccessorImpl.resetCloudFoundryClient and related increase in DirectByteBuffer count and total size.

## Expected Behavior
Zero net increase in cloudfoundry-client-nio threads created for each call to ReactiveCFAccessorImpl.resetCloudFoundryClient. and no increase in DirectByteBuffer count and total size.

**Comment by checketts** [comment]
There was an inifinite retry bug in the previous CloudFoundry Java Client. Could you try version [0.7.3](https://github.com/promregator/promregator/releases/tag/v0.7.3) and let us know if you still see the behavior you describe?

**Comment by eaglerainbow** [comment]
Moreover, if you think that this is only caused by the connection watchdog, then please feel free to disable it by setting `cf.watchdog.enabled` = `false` (see also [configuration option](https://github.com/promregator/promregator/blob/39214d71d1f54ff4ce5fc9c6003716a96e5eb469/docs/config.md#option-cfwatchdogenabled-optional)).

**Comment by eaglerainbow** [comment]
> It seems as though resetCloudFoundryClient should either stop existing cloudfoundry-client-nio threads,

@checketts There is on point in the statement though: If the connection pool isn't properly disposed. We are just hoping that the garbage collector is good enough to mop it all up. 

I have created #163 which should assist here at least. Do you mind having a look and tell me what you think about that?

**Comment by eaglerainbow** [comment]
> This includes seemingly recoverable issues such as timed-out calls to the CF API.

Well, if the info request already times out with a (configurable) latency of 2.5 seconds (default value), then the connection pool deserves to be restarted.

**Comment by eaglerainbow** [comment]
>  A recommended -XX:MaxDirectMemorySize setting would be useful too.

Which deployment option (java package, maven or docker image) are you using?

**Comment by eaglerainbow** [comment]
Reopening due to pending discussion/analysis.

**Comment by mickey-hill** [comment]
> There was an inifinite retry bug in the previous CloudFoundry Java Client. Could you try version 0.7.3 and let us know if you still see the behavior you describe?

Issue is still present in 0.7.3

> I have created #163 which should assist here at least. Do you mind having a look and tell me what you think about that?

I don't have the background to have an opinion on whether this is the root cause.  It seems plausible, though.

> Moreover, if you think that this is only caused by the connection watchdog, then please feel free to disable it by setting cf.watchdog.enabled = false (see also configuration option).

Option is not available in 0.7.x (the 2.5 second timeout duration is hard coded too)

> Well, if the info request already times out with a (configurable) latency of 2.5 seconds (default value), then the connection pool deserves to be restarted.

Not configurable in 0.7.x.  Also - are you sure the connection pool deserves to be restarted?   ...maybe the issue is slowness on the CF API side.

> >A recommended -XX:MaxDirectMemorySize setting would be useful too.

> Which deployment option (java package, maven or docker image) are you using?

java package

Thank you!

**Comment by eaglerainbow** [comment]
> Issue is still present in 0.7.3

Thanks for the info. 
Are you able to run the current most recent version as of `master` in a test environment of yours?

> I don't have the background to have an opinion on whether this is the root cause. It seems plausible, though.

Thanks for your input 😄 
Initially I had meant it for checketts. 
In the meantime we have merge PR #163, which should dispose the previous set of connections.

> Option is not available in 0.7.x (the 2.5 second timeout duration is hard coded too)

You are right. Sorry, I had thought that it was already released. 

> Also - are you sure the connection pool deserves to be restarted? ...maybe the issue is slowness on the CF API side.

Well, that is why we made it switchable.
We have seen cases where resetting it helped a lot (for example, if CFCC has gone for maintenance mode and also the UAA is affected by this, leaving inconsistent tokens in the caches behind). 

In general, my personal opinion though is that if the CF API side (CFCC) does not respond within 2.5 seconds to the most trivial request that you could ever think of, then you should not expect that it will survive scraping possibly hundreds of different applications (and for that retrieving its metadata) in parallel with a periodicity of ~15s. Latency would jeopardize your results in Prometheus so badly, that its reliability would rather feel like looking into the Crystal Ball. Instead, the connection to the platform/the CFCC/whatever shall be fixed first, so that you get again reasonable response times (I would expect something <1s or so). 
I agree that resetting the connection looks like a reaction of despair - but in fact it's a rather reasonable approach to improve resilience (compared to burying our heads in the sand). 


>>    Which deployment option (java package, maven or docker image) are you using?
> java package

Then, please feel free to impose your own limitations on `XX:MaxDirectMemorySize`.
So far, there are little values of experience for this option (only checketts had posted some time back before - IIRC flat demand of 500k). If you get one, we could draft a documentation page on recommended values.

**Comment by eaglerainbow** [comment]
Internal remark: Manual test for number of thread pools needed here before closing

**Comment by eaglerainbow** [comment]
> Internal remark: Manual test for number of thread pools needed here before closing

Manually tested it by setting `cf.watchdog.timeout` to a very low value. This made the watchdog trigger very often. 
I saw some situations where temporarily two sets of `cloudfoundry-client-nio*` threads (in a pool) were running, but that situation was auto-resolving shortly thereafter.

**Comment by eaglerainbow** [comment]
With 72361f3c87596aca4875abb738c10e9a38ffe7cd the correction provided by #163 will be provided with 0.7.4 (once it will be released).

@mickey-hill How urgent is this correction for you?

**Comment by br-eye-an** [comment]
> With 72361f3 the correction provided by #163 will be provided with 0.7.4 (once it will be released).

> @mickey-hill How urgent is this correction for you?

i can wait a week without sweating this, maybe a bit longer.  how long were you thinking?

**Comment by eaglerainbow** [comment]
That statement is already sufficient for me. I'll try to create the 0.7.4 on next occasion.

**Comment by eaglerainbow** [comment]
I just released [0.7.4](https://github.com/promregator/promregator/releases/tag/v0.7.4). Please check if that helps!

**Comment by mickey-hill** [comment]
0.7.4 does not have the thread accumulation problem.  Thank you!
