### ISSUE TITLE
ResourceLeak

### ISSUE THREAD

**Issue by eloo** [promregator/promregator#66]
I've just found a new exception in the logs.
Looks like something went wrong during GarbageCollection.

```
 2018-07-30 07:29:12.684 ERROR 10 --- [y-client-nio-28] io.netty.util.ResourceLeakDetector       : LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:113)
	io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1889)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1270)
	io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221) 
```

Not sure if this is a real issue but i want to inform you about that

**Comment by eaglerainbow** [comment]
Thanks for the pointer.

Mmmhm.. That's a new one to me, too. 
Promregator does not use netty directly. However, I know that the CF Client library does so. 

Is this case reproducible for you somehow?
If yes, we should give it a try and tell it to the folks at https://github.com/cloudfoundry/cf-java-client/issues

**Comment by eloo** [comment]
yes its indirectly reproducable.. 
just set the maxRAM to a low value.. i guess i've tested 512mb

**Comment by eaglerainbow** [comment]
Just for the record: I just ran a small stress test on 07fbd81437a282cc4b0971d86be9183e3b395c18, trying to peak, if there was a memory leak in the system, but I could not spot one (did hprof snapshots after 1min of runtime and after 5min).

**Comment by eaglerainbow** [comment]
Having read through http://netty.io/wiki/reference-counted-objects.html, it's not the GC who is causing trouble here, but the internal ref-count implementation of io.netty (so, this even does not look like a problem "caused by" Promregator, but more is an indicator that the io.netty library, which is used by the CF Client lib is the culprit).

@eloo: If you want to do something good to the OS community, then have a look at http://netty.io/wiki/reference-counted-objects.html#troubleshooting-buffer-leaks . In a nutshell, they suggest you to start Promregator with
```
-Dio.netty.leakDetectionLevel=advanced
```
as JVM option and wait for the problem again. This enhances the stack trace which is generated in these situations. The latter then most likely will be of interest for the folks at https://github.com/netty/netty/issues . 

I currently don't see any way in helping here. That is why I would like to forward them to the folks at Netty.

**Comment by eloo** [comment]
@eaglerainbow thanks for clarification.
maybe you can add this to the documentation? like that 512mb maxRAM is not enough and can cause errors?

**Comment by eaglerainbow** [comment]
Ok, can do this.


Done with 2c43ea64cbebc01ca421d72ab7b70e1ca4c2a354
