### ISSUE TITLE
Option to set org and space using IDs

### ISSUE THREAD

**Issue by eloo** [promregator/promregator#89]
Hi,
we are sometimes getting timeouts when the org or space id is going to be fetched.. this is a small issue which can be easily resolved by settings the id's manually.. this will also make promregator a litte bit more stable. 

Yes, is know i can also increase the timeouts but reducing the pressure to the api is IMHO also a good side effect ;) 

The only drawback of such a change is that the user need to fetch the GUIDs manually, but this needs to be done only once. So for me this wouldn't be a huge problem.

@eaglerainbow What do you think?

**Comment by eaglerainbow** [comment]
I think I get your point, but the approach is not really convincing me. Here is why:
* Only taking the GUID would permit to bypass the initial discovery request for the id of orgs and spaces, but we still need the org's and space's name throughout later processing. One example for that is enrichment. In short this would mean that we just delay the problem from occurring - but still Promregator wouldn't be able to respond properly. 
* I don't think that your Cloud Controller is crashing due to the fact that we hammer too many requests on it (we anyhow have many straight-forward requests which are based on its primary key). If it can't stand the load, then the Cloud Controller anyhow has an issue. 
* Org and spaces are slow-changing objects. If you are able to fetch the GUID, because they don't change at all, you may also safely increase the timeouts significantly. 
* The org and space requests aren't the one's creating the big load anyway. It's the app's requests which are the trouble-makers -- especially if the timeout is quite low. And it's those GUIDs, which force us to perform discovery, as you can't hard-wire them in the config. It would be strange if you can fetch app GUIDs, but you can't fetch org/space GUIDs - as this all goes to the same service.

In short, I fear that the approach would just shift the problem to a different coding location, would be inconvenient for the admin and in the end would not really help to solve the issue.

Besides that I am currently struggling myself with a CF environment, where I observe strange Cloud Controller timeouts both if a proxy is enabled (see also #83), but also with different symptoms, if the proxy is out of the game (I haven't created an issue for this here, yet). My first analysis currently more points into the direction that either `netty-reactor` or even OpenJDK is to be blame for it (as I once had a network trace, where even the request wasn't sent - so that easy for the Cloud Controller to not answer and run into a timeout). I have less the impression that Promregator (or the `cf-java-client`) could do much about that. That is why I am currently tending more into the direction of asking why the request times out at all...

Or do you have any observation which points into a different direction?

**Comment by eloo** [comment]
@eaglerainbow 
okay, yes i agree with you. i missed the point that the space and org name is needed anyway.. 
and yes i can also see some weird behaviour in the requests when they timeout.. because promregator is not recovering at all and also the metrics for cf-fetch are looking good till it crashes once.. 
so maybe your guess with the netty reactor could be a good hint..

**Comment by eloo** [comment]
for me its fine to stay with the current solution 👍

**Comment by eaglerainbow** [comment]
Okay, thanks for the feedback - though I feel a little uncomfortable to close this issue, as it isn't really a solution yet for you 😟
