### ISSUE TITLE
Need a way to specify EXACT url route of application when they are multiple routes linked

### ISSUE THREAD

**Issue by tbua** [promregator/promregator#91]
## Environment
promregator version 0.6.0; deployed with .jar file; CF api version 2.112.0

## Summary / Problem Statement
I have multiple routes associated with 1 App. For example, the 2 routes (urls): `abc.domaina `and `abc.domainb `are both associated with app 'abc'. I need a way to tell promregator which **EXACT url endpoint** to scrape from because now it's scraping from wrong endpoint. 

## Observed Behavior
With promregator, you can only specify app name. Then promregator does some sort of mechanism to scrape metrics from one of the routes. But that route might not be a valid endpoint.

The problem I'm facing now: 
One of the url endpoint, say `abc.domaina`, was not set up properly and was giving errors regarding to ssl certificate, SSLPeerUnverifiedException (error nothing to do with promregator). However the other route, say `abc.domainb`, has proper certificate and will not face this problem if it is used, but promregator somehow picks route `abc.domaina` over route `abc.domainb` when scraping metrics. Is there a way to define exact route(url) for each target? 

## Expected Behavior
We should be able to define which route promregator should be scraping from, not just let it determine by itself. Prometheus has the option where you can directly specify the url, but promregator only has app name and path, but not domain name. Help please/

**Comment by tbua** [comment]
I found the code I believe:
It's getting index(0) of the url list. 

![image](https://user-images.githubusercontent.com/18537340/53936450-613ed000-40dc-11e9-8102-aa94531c6a3e.png)

**Comment by eaglerainbow** [comment]
Hi tbua,
welcome to Promregator!
I think I understand your case quite well - and yes, you already found the [right location of the coding](https://github.com/promregator/promregator/blob/8b9f2165cbced42e9babe2e9dd3de3000c25374c/src/main/java/org/cloudfoundry/promregator/scanner/ReactiveAppInstanceScanner.java#L122), which causes the effect you observe. Already when I wrote that piece of code more than half a year ago, I knew that this might not be the ideal solution -- but I did not know what would be the *right* way to make it better. I was simply lacking the appropriate use case for that. Here it comes now 😀 

That's why I would like to discuss with you, which way we should take. Can you give us a little more insight on your environment of your case (in an anonymous form, for sure), please? Serving as "guiding questions" the following items might help us to find the right design for your problem:

* How many apps use `domaina`?
* Do you have influence on the sequence of the routes when they are created/bound?
* Do you want to forbid a certain single URL only?
* Do you want to forbid a certain entire domain (and all its associated routes)?
* Do you want to forbid a certain pattern of domain names?
* Do you want to pick the index of the *route* individually?
* Do you want to explicitly specify which *domain* shall be chosen?
* Shall such a positive-selection be exclusive - or only indicating preference / priority? 
   * If it is exclusive, what kind of error handling to you expect to happen in case the selection of the route fails (e.g. the expected route does not exist)?
   * If it's a priority, how many levels of priorities do you need? One or many?
* Is ignoring the error in the SSL certificate for the case of scraping a (fallback?) option for you (because the connection between Promregator and the CF app cell is trusted already anyhow)?
* Where/how do you want to configure your choice? On individual target level? What happens in case that you use "regex"es in the target configuration, which may select multiple applications (potentially in different spaces&orgs) at once?

In short, share your problem with us in a little more detail and what would help you, such that we can make Promregator better for everyone 😄

**Comment by eaglerainbow** [comment]
@bkez322 In issue #36 you also had reported a similar case. Would such a feature also help in your environment?

**Comment by tbua** [comment]
Hi @eaglerainbow 
Thanks for the quick response. 

We found out that problem comes from our cloudfoundry UI and did a workaround to fix it temporarily. 

TLDR; To describe the problem: in the UI, there's only the option to create and unmap route (X-button that we thought was for deleting) but not to delete or to rank it. We tried unmapping both routes, `domaina `and `domainb`, from the list. Then remapped `domainb `first, in hope that the default routes will be change from `domaina `to `domainb`. But that doesn't work.

We tried a different method on CF CLI. After unrouting it, we perform `cf routes` on CLI and notice that even though it had been deleted, that exact host and domain pair still exist in the list. So, when we remap the route, the ranking doesnt change as the entry will be reused. When a NEW route is mapped to the same app, another entry gets created but prioritizes below all other existing entries. 

The fix we found was to perform a 'cf delete-route' to completely remove the entry from the table. Then add the desired route before all others so it becomes the 'default' route for the app.

For me at this point, if it has 'targets' option like prometheus config file, it's great enough.

**Comment by tbua** [comment]
Here's my answers:
- How many apps use domaina?
Many components are using domaina. In fact all of them are using both a and b. (One internal, one external)
- Do you have influence on the sequence of the routes when they are created/bound?
No I dont. Another team member did it.
Do you want to forbid a certain single URL only?
No I dont want to forbid anything. (whitelist smaller than blacklist)
Do you want to forbid a certain entire domain (and all its associated routes)?
No.
Do you want to forbid a certain pattern of domain names?
No
- Do you want to pick the index of the route individually?
No. I don't know which index is which. I can find out via CLI if I try to count, but other team members may not know.
- Do you want to explicitly specify which domain shall be chosen?
Yes. Or even better the Exact URL route. 
- Shall such a positive-selection be exclusive - or only indicating preference / priority?
It could be the default route. If it doesnt exist, other discovered route can be reuse.
- If it is exclusive, what kind of error handling to you expect to happen in case the selection of the route fails (e.g. the expected route does not exist)?
It's working nicely with existing promregator_up{} metrics already.
- If it's a priority, how many levels of priorities do you need? One or many?
This sounds like a lot of work for you. And might be too advanced for users like me at this point.
- Is ignoring the error in the SSL certificate for the case of scraping a (fallback?) option for you (because the connection between Promregator and the CF app cell is trusted already anyhow)?
Would this open a vulnerabilities like MITM? I know you have options like `skipSslValidation`. 
- Where/how do you want to configure your choice? On individual target level? What happens in case that you use "regex"es in the target configuration, which may select multiple applications (potentially in different spaces&orgs) at once?

For me at this point, if it has 'targets' option like prometheus config file, it's great enough.

**Comment by eaglerainbow** [comment]
Thanks for your feedback. The answers are already helping me to get your point better.

> No I dont want to forbid anything. (whitelist smaller than blacklist)

Okay, so we are on a whitelist approach.

> For me, at this point, if promregator has 'targets' option like prometheus config file, it's great enough.

Well, that I can understand, but it would only do the trick, if you are selecting single instances explicitly. Several other users requested the feature to regex-select targets (and thus doing an extended form of discovery) as otherwise their config would be huge and cumbersome to set up. So, to keep both parties happy, we need to find a compromise.

> Do you want to explicitly specify which domain shall be chosen?
> Yes. Or even better the Exact URL route.

I think, here is the point of the compromise: Specifying the exact route is only possible, if your target selection is non-regex-ish. If it can hit multiple apps on CF, specifying a single route simply doesn't make much sense (as it would hit only one app, or you had to know all the routes in advance, what you cannot do). If we only specify in the configuration of the Prometheus-target the domain, then this could be generic enough to also apply to all applications in the selection. On the other hand, it may make writing the regexes much more complicated in case such a domain-limiting configuration should only apply to a subset of apps within the selection. However, it may turn out that this is just some theoretical problem and does not happen in real life.


I'll think about an approach along these lines - and will let you know...

----

> Would this open a vulnerabilities like MITM? I know you have options like skipSslValidation.

Yes, it would. That was the reason for my extension to the question question which read "because the connection between Promregator and the CF app cell is trusted already anyhow".

**Comment by eaglerainbow** [comment]
Mmmh... just a couple of minutes ago, I pushed an enhancement to `master`, which might already do the trick. You may find the implementation at https://github.com/promregator/promregator/commit/9315dd9cde7a7e0c1547fa25696dd03f79067f7e.

As you might have noticed from earlier issues, I very much love to get early feedback. That is why I would kindly ask you to test, if the feature is giving you what you want.  To test it, you have to set the configuration of a target like this:

```yaml
  targets:
    - orgName: someOrgName
      spaceName: someSpaceName
      applicationName: someAppName
      preferredRouteRegex:
       - ".*aStringThatAppearsInYourRoute.*"
```

Here is `preferredRouteRegex` in a nutshell:
* When Promregator needs to determine which route to take, it will run through the `preferredRouteRegex`es defined in the configuration. 
* Each line (which YAML requires to start with a hyphen) is a regular expression for the *entire* route to match. As entering a Regex in a YAML file can be tricky, it is *highly recommended* to put them into quotes (").
* If you want to explicitly match a single route, simply enter the full route's string verbatimly. Keep in mind, though, that it is a regex, so you should escape the dots (`.` => `\.`).
* The first regex matching will be taken (i.e the order of the list is considered; thus, we also have priority implemented already).
* If no regex matches (or no `preferredRouteRegex` was provided), Promregator reverts back to the old logic: taking the first route provided by CF.

I'd love to hear your feedback on this!


----

For the records: There still official documentation missing on this.

**Comment by checketts** [comment]
@eaglerainbow Thanks for adding this feature. I'm running into this myself.  So if I had the following 3 routes:

```
  routes:
  - route: my-app.app.org/api
  - route: my-app.app.org/login
  - route: my-app.app.org/logout
  - route: my-app.app.org/authenticate
  - route: my-app.app.org/management
```

I want it to use the `management` route. However then it concatenates the `path` to the route. Is there a way to tell it to just use the domain from the route and use the path as is?

**Comment by eaglerainbow** [comment]
@checketts I think your problem is related to this issue, but might be a different one. 
Would you mind creating a new issue for that -- and provide a little more details on your existing configuration? My gut-feeling is that there is yet another problem in your configuration which should be fixed first.

**Comment by eaglerainbow** [comment]
Just for the record (internal remark) on the case checketts has raised: The scenario already works for my own little "/dummy" test scenario:
* `path: /metrics`
* The route contains a path prefix with "/dummy"
* ```
   preferredRouteRegex:
      - ".*dummy.*"
   ```

**Comment by eaglerainbow** [comment]
NB: as mentioned in #114: Documentation still missing prior to release

**Comment by eaglerainbow** [comment]
on test confirmation see also https://github.com/promregator/promregator/issues/114#issuecomment-517312115 where @jensbaitingerbosch confirmed that it worked for him.

**Comment by WilliamLHarms** [comment]
I believe that I'm running into the same problem.  My applicaiton has 2 routes on each cloud instance, one route is common that sits behind an F5  big-foo.someCompany.com The other routes are:
- big-foo.xxx01.someCompany.com
- big-foo.yyy01.someCompany.com

When I add the "preferredRouteRegex" set it to .*yyy01.* , and I turn up debug mode on the promregator, it's not picking up the new route and just giving me back 404's on big-foo.someCompany.com.   

I'm using  promregator-0.5.7.jar

**Comment by eaglerainbow** [comment]
@WilliamLHarms : Thanks for reporting your case here and all your effort to try running it. 
Are you aware of the fact that this feature is only available after commit 9315dd9cde7a7e0c1547fa25696dd03f79067f7e, which currently is only available to `master` (which will eventually become 0.6.0)? The 0.5.x codeline never saw this feature (being in maintenance) and presumably will never do so.  Yet, we don't have a release candidate for 0.6.0 yet either, so this is just available in code yet (and not in binary form). 
Are you able to create your own binary based on `master` for your tests?

>  I even tried with the . to escape them in the regex, That actually threw an error in the parser when firing up promregator.

What did you write exactly? Did you yaml-escape it properly?
It might be something for documentation...

**Comment by eaglerainbow** [comment]
Note that I have released 0.6.0 in the meantime. The feature discussed here is included in this release. 0.5.x did not receive it. 

@WilliamLHarms In case you still encounter issues, please feel free to open this ticket here again!

**Comment by WilliamLHarms** [comment]
Thank you Nico, this will be a great help for cloud to cloud failover.

On Aug 17, 2019, at 4:49 PM, Nico Schmoigl <notifications@github.com<mailto:notifications@github.com>> wrote:


Note that I have released 0.6.0 in the meantime. The feature discussed here is included in this release. 0.5.x did not receive it.

@WilliamLHarms<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_WilliamLHarms&d=DwMCaQ&c=vtLDwE1j-r1Jx3yyA8ilTg&r=39k4NOlsR1zyU_sooF1lkzFELRn4xstss8SnG56we-U&m=08ASx3LoEAUxCVlrFBcQNRi2jUApqxD0-SSMTjZDsdU&s=Tc4arLBsXMIutfrzWoYYWB7E2FVIJSH7ZrNSlRENdpc&e=> In case you still encounter issues, please feel free to open this ticket here again!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_promregator_promregator_issues_91-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAI6ZFMAAFPZRIUY7STP6KDLQFBP6PA5CNFSM4G4JYCG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4QTHII-23issuecomment-2D522269601&d=DwMCaQ&c=vtLDwE1j-r1Jx3yyA8ilTg&r=39k4NOlsR1zyU_sooF1lkzFELRn4xstss8SnG56we-U&m=08ASx3LoEAUxCVlrFBcQNRi2jUApqxD0-SSMTjZDsdU&s=qmwXUxj4-pe4X_-INfWGLz7nbIV0M8iYUXKwQjw7RZs&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AI6ZFMARBWNMY6FPLRYBP63QFBP6PANCNFSM4G4JYCGQ&d=DwMCaQ&c=vtLDwE1j-r1Jx3yyA8ilTg&r=39k4NOlsR1zyU_sooF1lkzFELRn4xstss8SnG56we-U&m=08ASx3LoEAUxCVlrFBcQNRi2jUApqxD0-SSMTjZDsdU&s=Fa_pViZXN7XOY7WJ-3zMLYT0kacVG4S2qpCQkf3j4xI&e=>.

The information contained in this message and any attachments (collectively, the "Transmission") from Dick's Sporting Goods, Inc. or one of its subsidiaries contains confidential information and is intended solely for the named recipient(s). If you are not a named recipient, you are prohibited from copying, distributing or using this Transmission. Please contact the sender immediately by returning the e-mail and deleting the original Transmission.

**Comment by WilliamLHarms** [comment]
@eaglerainbow - Just tested and the new version accepts the new patterns mentioned in this ticket.  Thanks for the help and the release on the weekend.  

As for your question on the error I get when escaping the .'s

```
    - orgName: myOrg
      spaceName: prod
      applicationName: myapp
      path: /actuator/prometheus
      preferredRouteRegex:
       - "myapp\.company\.com"

```

```
 - Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a double-quoted scalar
 in 'reader', line 45, column 10:
           - "in
             ^
found unknown escape character .(46)
 in 'reader', line 45, column 21:
   myapp\.company\.com"
              ^

```

Taking the \'s out works.

**Comment by eaglerainbow** [comment]
@WilliamLHarms 
Thanks for the feedback!
Note that in YAML, backslash itself is being used for escaping (see also https://yaml.org/spec/1.2/spec.html, section 5.7, block 62). Thus, what you are saying with the double-quotes and the single backslash is that you want to escape the dot in YAML --- which does not know how to do that. Instead, you want to have the dot as of Java Regex to be escaped - and that requires a backslash in the string (coming from YAML). So, the Right Answer™️  most likely in your case would be:
```yaml

    - orgName: myOrg
      spaceName: prod
      applicationName: myapp
      path: /actuator/prometheus
      preferredRouteRegex:
       - "myapp\\.company\\.com"
```

Alternatively you may also use single-quotes, which are used to make strings verbatim in YAML (section 7.3.2, 4th sentence). 

I'll add another remark to the documentation on this, as I think someone else might stumbled over that, too...

**Comment by WilliamLHarms** [comment]
@eaglerainbow  - having some problems with this on 0.6.2, we have 3 routes configured:
```
https://acme-prod.xxx.com
https://acme-prod-green.apps.ap01.xxx.com
https://acme-prod.apps.ap01.xxx.com
```
and my yaml is this
```
    - orgName: acme-company
      spaceName: prod
      applicationName: acme-prod-green
      path: /actuator/prometheus
      perferredRouteRegex:
        - '.*ap01.*'
```

And the logs show:
```
onNext(IntermediateTarget [configTarget=Target [orgName=acme-company, orgRegex=null, spaceName=prod, spaceRegex=null, applicationName=acme-prod-green, applicationRegex=null, path=/actuator/prometheus, protocol=null, authenticatorId=null, preferredRouteRegex=null], resolvedOrgName=order-sourcing, resolvedOrgId=SECRET, resolvedSpaceName=prod, resolvedSpaceId=SECRET, resolvedApplicationName=acme-prod-green, resolvedApplicationId=SECRET])
```

Does that mean that the perferredRouteRegex is not loaded?  Or not being considered?

When turning things up to trace the routes are:
```
host=acme-prod-green, id=SECRET, path=, port=null}, Route{domain=Domain{id=secret, internal=null, name=apps.ap01.pcf.XXX.com, owningOrganizationId=null, routerGroupId=null, routerGroupType=null}, host=acme-prod, id=SECRET, path=, port=null}], runningInstances=1, serviceCount=2, serviceNames=[secret1, secret2], urls=[acme-prod.XXX.com, acme-prod-green.apps.ap01.pcf.XXX.com, acme-prod.apps.ap01.pcf.XXX.com], 
```

yields:
```
o.c.p.s.ReactiveAppInstanceScanner       : Using Application URL: 'https://acme-prod.XXX.com'
```

It seems like the regex isn't being loaded corretly into the router picker.

**Comment by eaglerainbow** [comment]
@WilliamLHarms 
Is 
```yaml
perferredRouteRegex:
```
just a typo (it should read `preferredRouteRegex` instead) here in your post, or is the typo also in your configuration?

**Comment by WilliamLHarms** [comment]
Yes that worked.  Sorry for the PEBCAK.  It's been a long two weeks.

**Comment by eaglerainbow** [comment]
> Sorry for the PEBCAK. 

No prob. Errare humanum est.

> Yes that worked. 

I am just glad that we could solve it so easily.

>  It's been a long two weeks.

Yeah, here too!
